/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    flavors: Flavor;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    flavors: FlavorsSelect<false> | FlavorsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flavors".
 */
export interface Flavor {
  id: number;
  name: string;
  /**
   * Order in which flavors appear in the carousel (ascending)
   */
  order?: number | null;
  bottle750?: (number | null) | Media;
  /**
   * Optional fallback URL if no media file is selected above.
   */
  bottle750Url?: string | null;
  bottle375?: (number | null) | Media;
  /**
   * Optional fallback URL if no media file is selected above.
   */
  bottle375Url?: string | null;
  bottle160?: (number | null) | Media;
  /**
   * Optional fallback URL if no media file is selected above.
   */
  bottle160Url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | HeroBlock
        | SaboresBlock
        | TwoColBlock
        | SaintManichoBlock
        | HistoriaBlock
        | DondeEncontrarnosBlock
        | {
            eyebrow?: string | null;
            title?: string | null;
            sub?: string | null;
            formAction?: string | null;
            subject?: string | null;
            submitText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactoBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  title: string;
  subtitle?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  videoSrc?: string | null;
  posterImage?: (number | null) | Media;
  posterUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SaboresBlock".
 */
export interface SaboresBlock {
  eyebrow?: string | null;
  autoPlayMs?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'saboresBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColBlock".
 */
export interface TwoColBlock {
  columns?:
    | (
        | {
            image?: (number | null) | Media;
            imageUrl?: string | null;
            alt?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            tag?: string | null;
            title: string;
            description?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            image?: (number | null) | Media;
            imageUrl?: string | null;
            theme?: ('maroon' | 'dark' | 'cream') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardBlock';
          }
      )[]
    | null;
  /**
   * Optional fallback: used if no column blocks are added above.
   */
  imagePath?: string | null;
  altText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoColBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SaintManichoBlock".
 */
export interface SaintManichoBlock {
  imagePath?: string | null;
  altText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'saintManichoBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HistoriaBlock".
 */
export interface HistoriaBlock {
  wordmarkImage?: (number | null) | Media;
  wordmarkImageUrl?: string | null;
  scriptText?: string | null;
  paragraph1?: string | null;
  paragraph2?: string | null;
  sinceText?: string | null;
  signText?: string | null;
  mediaImage?: (number | null) | Media;
  mediaImageUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'historiaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DondeEncontrarnosBlock".
 */
export interface DondeEncontrarnosBlock {
  title?: string | null;
  places?:
    | {
        city: string;
        logo1?: string | null;
        logo2?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dondeEncontrarnosBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'flavors';
        value: number | Flavor;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flavors_select".
 */
export interface FlavorsSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  bottle750?: T;
  bottle750Url?: T;
  bottle375?: T;
  bottle375Url?: T;
  bottle160?: T;
  bottle160Url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        heroBlock?: T | HeroBlockSelect<T>;
        saboresBlock?: T | SaboresBlockSelect<T>;
        twoColBlock?: T | TwoColBlockSelect<T>;
        saintManichoBlock?: T | SaintManichoBlockSelect<T>;
        historiaBlock?: T | HistoriaBlockSelect<T>;
        dondeEncontrarnosBlock?: T | DondeEncontrarnosBlockSelect<T>;
        contactoBlock?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              sub?: T;
              formAction?: T;
              subject?: T;
              submitText?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  videoSrc?: T;
  posterImage?: T;
  posterUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SaboresBlock_select".
 */
export interface SaboresBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  autoPlayMs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColBlock_select".
 */
export interface TwoColBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        imageBlock?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
              id?: T;
              blockName?: T;
            };
        cardBlock?:
          | T
          | {
              tag?: T;
              title?: T;
              description?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              image?: T;
              imageUrl?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
      };
  imagePath?: T;
  altText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SaintManichoBlock_select".
 */
export interface SaintManichoBlockSelect<T extends boolean = true> {
  imagePath?: T;
  altText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HistoriaBlock_select".
 */
export interface HistoriaBlockSelect<T extends boolean = true> {
  wordmarkImage?: T;
  wordmarkImageUrl?: T;
  scriptText?: T;
  paragraph1?: T;
  paragraph2?: T;
  sinceText?: T;
  signText?: T;
  mediaImage?: T;
  mediaImageUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DondeEncontrarnosBlock_select".
 */
export interface DondeEncontrarnosBlockSelect<T extends boolean = true> {
  title?: T;
  places?:
    | T
    | {
        city?: T;
        logo1?: T;
        logo2?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logoPath?: string | null;
  subtitle?: string | null;
  navLinksLeft?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  navLinksRight?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logoPath?: string | null;
  topLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'whatsapp' | 'instagram' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  bottomMenu?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  designedByText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteTitle?: string | null;
  siteDescription?: string | null;
  favicon?: (number | null) | Media;
  faviconUrl?: string | null;
  /**
   * Enlace de WhatsApp para el botón flotante de acceso rápido (ej. https://wa.me/593999999999 o +593999999999). Si se deja vacío, el botón flotante no se mostrará.
   */
  whatsappUrl?: string | null;
  /**
   * Muestra un popup al ingresar requiriendo confirmación de mayoría de edad.
   */
  enableAgeGate?: boolean | null;
  ageGateTitle?: string | null;
  ageGateMessage?: string | null;
  ageGateConfirmText?: string | null;
  ageGateRejectText?: string | null;
  underageTitle?: string | null;
  underageMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logoPath?: T;
  subtitle?: T;
  navLinksLeft?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  navLinksRight?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logoPath?: T;
  topLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  bottomMenu?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  designedByText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteDescription?: T;
  favicon?: T;
  faviconUrl?: T;
  whatsappUrl?: T;
  enableAgeGate?: T;
  ageGateTitle?: T;
  ageGateMessage?: T;
  ageGateConfirmText?: T;
  ageGateRejectText?: T;
  underageTitle?: T;
  underageMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}